//! P2-обход: AOT-компиляция обратимых ядер в нативный код.
//!
//! Интерпретатор ~3.7–16 ns/leaf; нативный код — порядок быстрее. Модуль
//! генерирует C-функции `phase_fwd`/`phase_rev` из ядра (L0/L1: Inst + Rep,
//! без decision-журнала); их компилирует `cc -O2 -shared`, грузит dlopen.
//! rep раскрывается в цикл C; rev структурный (только чисто обратимое ядро).

use crate::inst::Inst;
use crate::program::Node;

const HEADER: &str = r#"/* generated by phase-vm aot */
#include <stdint.h>
#define ROL(x,k) (((x)<<(k))|((x)>>((64-(k))&63)))
#define ROR(x,k) (((x)>>(k))|((x)<<((64-(k))&63)))
"#;

fn tmp(tmpc: &mut u32) -> String {
    *tmpc += 1;
    format!("t{}", *tmpc)
}

fn gen_leaf(i: &Inst, tmpc: &mut u32) -> String {
    use Inst::*;
    match *i {
        Nop => String::new(),
        Not(x) => format!("r[{x}]=~r[{x}];"),
        Inc(x) => format!("r[{x}]++;"),
        Dec(x) => format!("r[{x}]--;"),
        Xor(d, s) => format!("r[{d}]^=r[{s}];"),
        Add(d, s) => format!("r[{d}]+=r[{s}];"),
        Sub(d, s) => format!("r[{d}]-=r[{s}];"),
        Swap(a, b) => {
            let n = tmp(tmpc);
            format!("{{ uint64_t {n}=r[{a}]; r[{a}]=r[{b}]; r[{b}]={n}; }}")
        }
        RotL(_x, k) if (k & 63) == 0 => String::new(),
        RotL(x, k) => format!("r[{x}]=ROL(r[{x}],{});", k & 63),
        RotR(_x, k) if (k & 63) == 0 => String::new(),
        RotR(x, k) => format!("r[{x}]=ROR(r[{x}],{});", k & 63),
        Toff(c1, c2, x) => format!("r[{x}]^=r[{c1}]&r[{c2}];"),
        CSwap(c, a, b) => {
            let n = tmp(tmpc);
            format!("{{ if (r[{c}]&1) {{ uint64_t {n}=r[{a}]; r[{a}]=r[{b}]; r[{b}]={n}; }} }}")
        }
        Set(x, v) => format!("r[{x}]={}ULL;", v),
        MAdd(a, v) => format!("m[r[{a}]]+=r[{v}];"),
        MSub(a, v) => format!("m[r[{a}]]-=r[{v}];"),
        MXor(a, v) => format!("m[r[{a}]]^=r[{v}];"),
        RAdd(x, a) => format!("r[{x}]+=m[r[{a}]];"),
        RSub(x, a) => format!("r[{x}]-=m[r[{a}]];"),
        MSet(a, v) => format!("m[{a}]={}ULL;", v),
    }
}

fn gen_nodes(nodes: &[Node], rev: bool, tmpc: &mut u32) -> String {
    let mut out = String::new();
    if !rev {
        for node in nodes {
            match node {
                Node::Inst(i) => out.push_str(&gen_leaf(i, tmpc)),
                Node::Rep { count, body } => {
                    let body = gen_nodes(body, false, tmpc);
                    if !body.is_empty() {
                        out.push_str(&format!(
                            "{{ for (uint64_t _i=0;_i<{count};_i++) {{ {body} }} }}"
                        ));
                    }
                }
            }
            out.push('\n');
        }
    } else {
        for node in nodes.iter().rev() {
            match node {
                Node::Inst(i) => {
                    if let Some(inv) = i.inverse() {
                        out.push_str(&gen_leaf(&inv, tmpc));
                    }
                }
                Node::Rep { count, body } => {
                    let body = gen_nodes(body, true, tmpc);
                    if !body.is_empty() {
                        out.push_str(&format!(
                            "{{ for (uint64_t _i=0;_i<{count};_i++) {{ {body} }} }}"
                        ));
                    }
                }
            }
            out.push('\n');
        }
    }
    out
}

/// Сгенерировать C с phase_fwd/phase_rev. rev — только для чисто обратимого
/// ядра, иначе пустая функция (откат через границы требует чекпоинта).
pub fn codegen(nodes: &[Node]) -> String {
    let mut t = 0u32;
    let fwd = gen_nodes(nodes, false, &mut t);
    let rev_body = if crate::check::check(nodes).reversible() {
        t = 0;
        gen_nodes(nodes, true, &mut t)
    } else {
        "/* kernel has boundaries: reverse requires a checkpoint */".to_string()
    };
    format!(
        "{HEADER}\n\
         void phase_fwd(uint64_t* r, uint64_t* m, uint64_t _ml) {{\n{fwd}\n}}\n\n\
         void phase_rev(uint64_t* r, uint64_t* m, uint64_t _ml) {{\n{rev_body}\n}}\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::program::parse;

    #[test]
    fn codegen_contains_functions() {
        let nodes = parse("set r0 5\nadd r0 r1\nrotl r1 7\nrep 4\nxor r2 r0\nend\n", 8)
            .unwrap()
            .nodes;
        let c = codegen(&nodes);
        assert!(c.contains("phase_fwd"));
        assert!(c.contains("for (uint64_t _i=0;_i<4;_i++)"));
        assert!(c.contains("r[0]+=r[1]"));
    }

    #[test]
    fn codegen_rev_empty_when_boundaries() {
        let nodes = parse("set r0 5\nadd r0 r1\n", 8).unwrap().nodes;
        let c = codegen(&nodes);
        assert!(c.contains("requires a checkpoint"));
    }

    #[test]
    fn rev_codegen_has_inverses_for_pure_kernel() {
        let nodes = parse("add r0 r1\nrotl r1 7\nxor r1 r0\n", 8).unwrap().nodes;
        let c = codegen(&nodes);
        assert!(c.contains("r[0]-=r[1]"));
        assert!(c.contains("ROR(r[1],7)"));
    }
}
